spring:
  profiles:
    active: ES,dog
db:
  username: yml username
  password: yml pass
  jdbcurl: yml dburl

---
spring:
  config:
    activate:
      on-profile: prod
#spring:
#  profiles: prod
db:
  username: prod yml username
  password: prod yml pass
  jdbcurl: prod yml dburl
